version: "3.9"

services:
    web:
      image: fotoapp/latest
      build: 
         context: .
         dockerfile: Fotoquest.Api/Dockerfile
      ports:
         - 8000:80
      depends_on:
         - db

    db:
      image: "mcr.microsoft.com/mssql/server"
      environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=ZoopLe!1$$~2
      ports:
        - 1433:1433
        - 443:443
    
      
