version: "3.9"
services:

    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "ZoopLe!1$$~2"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"
        volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    web:
      build: 
         context: .
         dockerfile: dockerfile
      ports:
         - "8080:5167"
      image: fotoapp/latest
